//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class restEntities : DbContext
    {
        public restEntities()
            : base("name=restEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customerInfo> customerInfoes { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<menu> menus { get; set; }
        public virtual DbSet<order> orders { get; set; }
    
        public virtual ObjectResult<Nullable<int>> getNextSequenceValue()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("getNextSequenceValue");
        }
    }
}
